name: weather_app
description: Weather App project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^0.9.4
  cupertino_icons: ^1.0.0

  # UI
  custom_splash: 0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0
  build_runner: 1.11.1
  flutter_launcher_icons: 0.8.1
  flutter_launcher_name: 0.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/ic_launcher_android.png"
  image_path_ios: "assets/images/ic_launcher_iOS.png"


flutter_launcher_name:
  name: "Weather App"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
