name: weather_app
description: Weather App project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^0.9.4
  cupertino_icons: ^1.0.0
  intl: ^0.16.1

  # UI
  custom_splash: 0.0.2

  # NETWORK
  dio: ^3.0.10

  # Storage
  sqflite: ^1.3.2+3
  path: ^1.7.0
  freezed_annotation: ^0.12.0

  # STATE MANAGEMENT
  flutter_bloc: ^6.1.2
  equatable: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0
  build_runner: 1.11.1
  freezed: ^0.12.2
  json_serializable: ^3.3.0
  flutter_launcher_icons: 0.8.1
  flutter_launcher_name: 0.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/brand/ic_launcher_android.png"
  image_path_ios: "assets/images/brand/ic_launcher_apple.png"


flutter_launcher_name:
  name: "Weather App"


flutter:
  uses-material-design: true
  assets:
    - assets/images/brand/
    - assets/images/weather/color/
    - assets/images/weather/black/
    - assets/images/weather/grey/
